### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by stridejoe** [seothemes/genesis-starter-theme#22]
## Submit a feature request or bug report

- [ X] I've read the [guidelines for Contributing](https://github.com/seothemes/genesis-starter-theme/blob/master/.github/CONTRIBUTING.md)
- [ ] This is a feature request
- [ X] This is a bug report
- [ X] This request isn't a duplicate of an [existing issue](https://github.com/seothemes/genesis-starter-theme/issues)
- [ X] This is not a personal support request that should be asked via [SEO Themes Support](https://seothemes.com/support)

---

**What is the current behavior?**

All I have installed all the pre-reqs and tried both the one line and individuals commands for installation and have two consistent issues. I'm new to composer and Genesis in general so thanks 
for your patience and assistance. If there is more detailed documentation for setup I'll gladly give it a whirl. Seems like an awesome theme if I can get it running! 

Issue #1 is post sh setup

fs.js:113
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/seothemes/.valet/Certificates/http://localhost/wordpress/stridethemeone/.key'
    at Object.openSync (fs.js:434:3)
    at Object.readFileSync (fs.js:339:35)
    at getKey (/Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/node_modules/browser-sync/dist/server/utils.js:38:15)
    at getHttpsServerDefaults (/Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/node_modules/browser-sync/dist/server/utils.js:45:14)
    at Object.getHttpsOptions (/Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/node_modules/browser-sync/dist/server/utils.js:67:41)
    at /Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/node_modules/browser-sync/dist/server/utils.js:81:44
    at Object.getServer (/Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/node_modules/browser-sync/dist/server/utils.js:85:15)
    at createProxyServer (/Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/node_modules/browser-sync/dist/server/proxy-server.js:87:35)
    at createServer (/Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/node_modules/browser-sync/dist/server/index.js:69:41)
    at module.exports.plugin (/Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/node_modules/browser-sync/dist/server/index.js:12:20)

Obviously I don't have a user called seothemes and I've tried running composer create-project seothemes/genesis-starter-theme stride-theme-one dev-master with my user account or no account but haven't been successful. What is the correct command to run here? 

Issue #2 is on theme activation

Fatal error: Uncaught Error: Class 'D2\Core\ImageSizes' not found in /Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/config/defaults.php:228 Stack trace: #0 /Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/functions.php(33): require_once() #1 /Applications/MAMP/htdocs/wordpress/wp-includes/class-wp-hook.php(286): StrideThemeOne\StrideThemeOne\child_theme_setup('') #2 /Applications/MAMP/htdocs/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /Applications/MAMP/htdocs/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis/lib/init.php(384): do_action('genesis_setup') #5 /Applications/MAMP/htdocs/wordpress/wp-content/themes/genesis/functions.php(22): require_once('/Applications/M...') #6 /Applications/MAMP/htdocs/wordpress/wp-settings.php(426): include('/Applications/M...') #7 /Applications/MAMP/htdocs/wordpress/wp-config.php(96): require_once('/Applications/M...') #8 /Appl in /Applications/MAMP/htdocs/wordpress/wp-content/themes/stride-theme-one/config/defaults.php on line 228

**What is the expected or desired behavior?**

I'm expecting that the theme would be active and work. 

---

## Bug report

**Please provide steps to reproduce, including full log output:**

X

**Please describe your local environment:**

WordPress version: Version 4.9.8

OS: 10.13.5

NPM/Node version: 
npm: '6.2.0',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.32.0',
  node: '10.8.0',
  openssl: '1.1.0h',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.22.0',
  v8: '6.7.288.49-node.19',
  zlib: '1.2.11' 

**Where did the bug happen? Development or remote servers?**

X

---

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

X

**Comment by seothemes** [comment]
The first issue is caused by the BrowserSync config. It's setup to use an SSL by default, which is not ideal for most users. I've fixed this in a85c55ebae82afabc359001c0cedfa253892d4ed.

The second issue is being caused by an incorrect class name in the `d2/core-image-sizes` package. This should also be fixed now https://github.com/d2themes/core-image-sizes/commit/7b57d107d86303f5b3667dbd2453aefc9b52c969

Thank you for providing this information. Let me know if that fixes up the issue for you.

**Comment by antonyjsmith** [comment]
Still doesn't fix the image size issue, composer doesn't seem to be getting the latest version

**Comment by antonyjsmith** [comment]
I've added the core image sizes file manually to get past this issue and run into another:

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to D2\\Core\\PluginActivation::get_settings() must be of the type array, null given, called in /public_html/wp-content/themes/fiercegracemuswell/vendor/d2/core-plugin-activation/src/PluginActivation.php on line 109 and defined in /public_html/wp-content/themes/fiercegracemuswell/vendor/d2/core-plugin-activation/src/PluginActivation.php:145`

**Comment by seothemes** [comment]
@antonyjsmith I've created a new release for the ImageSizes component so it should now pull in the updated version. Note you will need to change it's version number in your composer.json from `"^0.1.0"` to `"^0.2.0"`.

For the PluginActivation error, can you please create a new issue at it's repository here - https://github.com/d2themes/core-plugin-activation/issues.

FYI, you can also remove packages if you are not using them, for example PluginActivation is only useful in commercial themes. If it's not needed just run `composer remove d2/core-plugin-activation` - then delete the component's config key from the return statement at the end of the `config/defaults.php` file.

**Comment by seothemes** [comment]
Reopening until resolved.
